[server]
hostname = "$env{HOST_NAME}"
node_ip = "127.0.0.1"
server_role = "api-publisher"
offset = "0"

[user_store]
type = "database"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.apim_db]
type = "mysql"
url = "jdbc:mysql://wso2am-mysql-db-service:3306/WSO2AM_DB?useSSL=false&amp;autoReconnect=true&amp;requireSSL=false&amp;verifyServerCertificate=false"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"

[database.shared_db]
type = "mysql"
url = "jdbc:mysql://wso2am-mysql-db-service:3306/WSO2AM_SHARED_DB?useSSL=false&amp;autoReconnect=true&amp;requireSSL=false&amp;verifyServerCertificate=false"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"

[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"

[truststore]
file_name = "client-truststore.jks"
type = "JKS"
password = "wso2carbon"

[[apim.gateway.environment]]
name = "Production and Sandbox"
type = "hybrid"
display_in_api_console = true
description = "This is a hybrid gateway that handles both production and sandbox token traffic."
service_url = "https://wso2am-pattern-3-gateway-service:${mgt.transport.https.port}${carbon.context}services/"
username= "${admin.username}"
password= "${admin.password}"

[transport.https.properties]
proxyPort = 443

[apim.analytics]
enable = "true"
receiver_username = "${admin.username}"
receiver_password = "${admin.password}"
store_api_url = "https://wso2am-pattern-3-analytics-worker-service:7444"
store_api_username = "${admin.username}"
store_api_password = "${admin.password}"

[[apim.analytics.url_group]]
analytics_url =["tcp://wso2am-pattern-3-analytics-worker-service:7612","tcp://wso2am-pattern-3-analytics-worker-2-service:7612"]
analytics_auth_url =["ssl://wso2am-pattern-3-analytics-worker-service:7712","ssl://wso2am-pattern-3-analytics-worker-2-service:7712"]
type = "failover"

# Traffic Manager configurations
[apim.throttling]
service_url = "https://localhost:${mgt.transport.https.port}${carbon.context}services/"
username= "$ref{super_admin.username}"
password= "$ref{super_admin.password}"

[[apim.throttling.url_group]]
traffic_manager_urls = ["tcp://wso2am-pattern-3-tm-1-service:9611"]
traffic_manager_auth_urls = ["ssl://wso2am-pattern-3-tm-1-service:9711"]
type = "loadbalance"

[[apim.throttling.url_group]]
traffic_manager_urls = ["tcp://wso2am-pattern-3-tm-2-service:9611"]
traffic_manager_auth_urls = ["ssl://wso2am-pattern-3-tm-2-service:9711"]
type = "loadbalance"

[apim.cache.scopes]
enable = true

[apim.cache.publisher_roles] #check the usage and move to dev role
enable = true

[apim.devportal]
url = "https://{{ .Release.Name }}-devportal/devportal"
